const docs = [{
    _id: "v1",
    youtubeId: "iX8GxLP1FHo",
    imdbPage: "https://www.imdb.com/title/tt4736550/",
    imageURL: "https://m.media-amazon.com/images/M/MV5BMGViZWEwOGItMGZlMC00YzE1LTk5ZWItMGYxYjhhMjBmNDMwXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_.jpg",
    title: "The Great Hack",
    description: "The Great Hack uncovers the dark world of data exploitation through the compelling personal journeys of players on different sides of the explosive Cambridge Analytica/Facebook data scandal.",
    tagline: "They Took Your Data. Then They Took Control.",
    genre: ["history", "technology"],
    language: ["English"],
    country: ["United States"],
    stats: {
      likes: "66K",
      dislikes: "1.7K",
      rating: {
        imdb: 7.1,
        rottenTomatoes: 87,
      },
    },
    tags: ["biography", "history", "trending", "data", "information", "crime"],
    officialSite: "Netflix",
    releaseDate: {
      day: 26,
      year: 2019,
      month: 1,
    },
    director: ["Karim Amer", "Jehane Noujaim"],
    durationMin: 139,
  },
  {
    _id: "v2",
    youtubeId: "gBaXUU8c-Mk",
    imdbPage: "https://www.imdb.com/title/tt3810760/",
    imageURL: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSiXS_V4WBvve0o_k8g7YketsVisafx0PcvxovRfQRMRrDY9azz",
    title: "Minimalism",
    tagline: "Imagine a life with less.",
    description: "How might your life be better with less? Minimalism: A Documentary About the Important Things examines the many flavors of minimalism by taking the audience inside the lives of minimalists from all walks of life -- families, entrepreneurs, architects, artists, journalists, scientists, and even a former Wall Street broker -- all of whom are striving to live a meaningful life with less.",
    genre: ["life style"],
    language: ["English"],
    country: ["United States"],
    stats: {
      likes: "",
      dislikes: "",
      rating: {
        imdb: 6.7,
        rottenTomatoes: 52,
      },
    },
    tags: ["life style", "people", "minimalism", "life", "less"],
    officialSite: "Netflix",
    releaseDate: {
      day: 26,
      year: 2020,
      month: 11,
    },
    director: ["Matt D'Avella"],
    durationMin: 79,
  },
  {
    _id: "v3",
    youtubeId: "Lrm2pD0qofM",
    imdbPage: "https://www.imdb.com/title/tt6939026/",
    imageURL: "https://kintsugispace.com/wp-content/uploads/2021/05/PEOS-Poster-Netflix-600w.jpg",
    title: "Period. End of Sentence.",
    description: "In rural India, where the stigma of menstruation persists, women make low-cost sanitary pads on a new machine and stride toward financial independence.",
    tagline: "",
    genre: ["women"],
    language: ["English", "Hindi"],
    country: ["United States"],
    stats: {
      likes: "",
      dislikes: "",
      rating: {
        imdb: 7.4,
        rottenTomatoes: 86,
      },
    },
    tags: ["oscar", "women", "motivation", "trending", "India"],
    officialSite: "Netflix",
    releaseDate: {
      day: 19,
      year: 2019,
      month: 2,
    },
    director: ["Rayka Zehtabchi"],
    durationMin: 25,
  },
  {
    _id: "v4",
    youtubeId: "WXuK6gekU1Y",
    imdbPage: "https://www.imdb.com/title/tt6700846/",
    imageURL: "https://m.media-amazon.com/images/M/MV5BYTU3ZjUxM2MtZWQ5OS00NDQxLTlhZDMtYzY3OTE4ZDY0NWM1XkEyXkFqcGdeQXVyMTc2NDg4MTU@._V1_.jpg",
    title: "AlphaGo",
    description: "With more board configurations than there are atoms in the universe, the ancient Chinese game of Go has long been considered a grand challenge for artificial intelligence. On March 9, 2016, the worlds of Go and artificial intelligence collided in South Korea for an extraordinary best-of-five-game competition, coined The DeepMind Challenge Match. Hundreds of millions of people around the world watched as a legendary Go master took on an unproven AI challenger for the first time in history.",
    tagline: "",
    genre: ["technology", "AI"],
    language: ["English"],
    country: ["United States"],
    stats: {
      likes: "",
      dislikes: "",
      rating: {
        imdb: 7.9,
        rottenTomatoes: 100,
      },
    },
    tags: ["AI", "trending", "technology", "go"],
    officialSite: "DeepMind",
    releaseDate: {
      day: 21,
      year: 2017,
      month: 4,
    },
    director: ["Greg Kohs"],
    durationMin: 90,
  },
  {
    _id: "v5",
    youtubeId: "8QlEZKI--pI",
    imdbPage: "https://www.imdb.com/title/tt6540256/",
    imageURL: "https://images-na.ssl-images-amazon.com/images/I/81EodhuttHL._RI_.jpg",
    title: "AFTER THE SEWOL",
    description: "‘After the Sewol’ explores the changing faces of this nation through the eyes of two British film makers. They talk with relatives of the victims, rescue divers and activists about their struggles and battles since this tragic accident happened and embark upon a journey to uncover how this accident came about, looking deep into Korean history about why no action was taken to prevent it in the first place.",
    tagline: "",
    genre: ["global", "tragedy"],
    language: ["Korean"],
    country: ["South Korea"],
    stats: {
      likes: "",
      dislikes: "",
      rating: {
        imdb: 7.6,
        rottenTomatoes: null,
      },
    },
    tags: ["global", "tragedy", "Asia"],
    officialSite: "Amazon",
    releaseDate: {
      day: "",
      year: 2017,
      month: "",
    },
    director: ["Neil George", "Matthew Root"],
    durationMin: 93,
  },
  {
    _id: "v6",
    youtubeId: "GfO-3Oir-qM",
    imdbPage: "https://www.imdb.com/title/tt9253866/",
    imageURL: "https://m.media-amazon.com/images/M/MV5BN2I1ZjA5YjQtYmQ0ZS00ZmE1LTk1ZjktNTQ5ODIzY2JiZDdhXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_.jpg",
    title: "Our Planet",
    description: "Experience our planet's natural beauty and examine how climate change impacts all living creatures in this ambitious documentary of spectacular scope.",
    tagline: "",
    genre: ["Environment"],
    language: ["English"],
    country: ["United States"],
    stats: {
      likes: "",
      dislikes: "",
      rating: {
        imdb: 9.3,
        rottenTomatoes: 93,
      },
    },
    tags: ["nature", "environment", "animals", "trending", "earth"],
    officialSite: "Netflix",
    releaseDate: {
      day: 5,
      year: 2019,
      month: 4,
    },
    director: [
      "Adam Chapman",
      "Hugh Pearson",
      "Huw Cordey",
      "Sophie Lanfear",
      "Mandi Stark",
      "Jeff Wilson",
    ],
    durationMin: 49,
  },
  {
    _id: "v7",
    youtubeId: "JaFVr_cJJIY",
    imdbPage: "https://www.imdb.com/title/tt1687247",
    imageURL: "https://upload.wikimedia.org/wikipedia/en/thumb/6/64/Lifeinaday_2011.jpg/215px-Lifeinaday_2011.jpg",
    title: "Life in a Day",
    description: "A documentary shot by film-makers all over the world that serves as a time capsule to show future generations what it was like to be alive on the twenty-fourth of July, 2010.",
    tagline: "Filmed by You",
    genre: ["People"],
    language: ["English", "Italian", "Japanese", "German", "Spanish", "Indonesian", "Balinese", "Portuguese", "Ukrainian", "Vietnamese", "Catalan", "Dutch", "Bengali", "Masai", "Hindi", "Arabic", "Quechua", "Russian"],
    country: ["United Kingdom", "United States"],
    stats: {
      likes: "",
      dislikes: "",
      rating: {
        imdb: 7.6,
        rottenTomatoes: 80,
      },
    },
    tags: ["life", "2010", "day in the life", "people", "global", "world"],
    officialSite: "YouTube",
    releaseDate: {
      day: 21,
      year: 2011,
      month: 1,
    },
    director: ["Kevin Macdonald", "Loressa Clisby", "Tegan Bukowski"],
    durationMin: 90
  }, {
    _id: "v8",
    youtubeId: "vcsSc2iksC0",
    imdbPage: "https://www.imdb.com/title/tt12706768/",
    imageURL: "https://resizing.flixster.com/a8dnnDtPM8nXNeKyUqiirvl50HU=/300x300/v2/https://flxt.tmsimg.com/assets/p19479289_v_h9_aa.jpg",
    title: "Life in a Day 2020",
    description: "On July 25th, 2020, people all over the world filmed their lives and shared their stories to be part of a documentary film. When all the submissions were tallied, the filmmakers had received over 300,000 videos from 192 countries. The result is a stirring film about love, death, heartbreak, and hope that looks beyond geography and circumstance to explore what connects us as humans.",
    tagline: "The Story of a Single Day on Earth.",
    genre: ["People"],
    language: ["English", "Italian", "Japanese", "German", "Spanish", "Indonesian", "Balinese", "Portuguese", "Ukrainian", "Vietnamese", "Catalan", "Dutch", "Bengali", "Masai", "Hindi", "Arabic", "Quechua", "Russian"],
    country: ["United Kingdom", "United States"],
    stats: {
      likes: "",
      dislikes: "",
      rating: {
        imdb: 7.2,
        rottenTomatoes: 68,
      },
    },
    tags: ["life", "2020", "day in the life", "people", "global", "world"],
    officialSite: "YouTube",
    releaseDate: {
      day: 6,
      year: 2021,
      month: 2,
    },
    director: ["Kevin Macdonald", "Howard Hong", "Danica Jensen"],
    durationMin: 90,
  }, {
    _id: "v9",
    youtubeId: "2yNDLxVmVw0",
    imdbPage: "https://www.imdb.com/title/tt3796080/",
    imageURL: "https://images-na.ssl-images-amazon.com/images/I/71+tn7w5PUL._RI_.jpg",
    title: "Madurai and Kerala | Rick Stein's India",
    description: "Rick Stein arrives in the southern town of Madurai in Tamil Nadu - the land of temples. He samples the famous south Indian sambar before taking a road trip across the spice laden Western Ghats to the land of coconuts, Kerala. Rick cooks south India's favourite dessert, payasam, and a traditional Keralan pork curry.",
    tagline: "",
    genre: ["Food"],
    language: ["English"],
    country: ["United Kingdom"],
    stats: {
      likes: "",
      dislikes: "",
      rating: {
        imdb: 8.3,
        rottenTomatoes: "",
      },
    },
    tags: ["India", "food", "bbc", "South India"],
    officialSite: "BBC Documentary",
    releaseDate: {
      day: 18,
      year: 2019,
      month: 9,
    },
    director: [],
    durationMin: 90,
  }, {
    _id: "v10",
    youtubeId: "M85UvH0TRPc",
    imdbPage: "https://www.imdb.com/title/tt3268458/",
    imageURL: "https://m.media-amazon.com/images/M/MV5BMjgwOTgwNjQ5MV5BMl5BanBnXkFtZTgwMzk1NTQ2MTE@._V1_.jpg",
    title: "The Internet's Own Boy",
    description: "The story of programming prodigy and information activist Aaron Swartz. From Swartz's help in the development of the basic internet protocol RSS to his co-founding of Reddit, his fingerprints are all over the internet. But it was Swartz's groundbreaking work in social justice and political organizing combined with his aggressive approach to information access that ensnared him in a two year legal nightmare. It was a battle that ended with the taking of his own life at the age of 26. Aaron's story touched a nerve with people far beyond the online communities in which he was a celebrity.",
    tagline: "Information is power",
    genre: ["Biography"],
    language: ["English"],
    country: ["United States"],
    stats: {
      likes: "",
      dislikes: "",
      rating: {
        imdb: 8,
        rottenTomatoes: 93,
      },
    },
    tags: ["biography", "crime", "information", "data"],
    officialSite: "",
    releaseDate: {
      day: 27,
      year: 2014,
      month: 6,
    },
    director: ["Brian Knappenberger"],
    durationMin: 100,
  }, {
    _id: "v7",
    youtubeId: "EexZjx3YOuQ&t=23s",
    imdbPage: "",
    imageURL: "https://cdn1.edgedatg.com/aws/v2/natgeotv/InsideNorthKorea/showimages/f5fd12bc3a778264f28011b7d3a90652/634x848-Q90_f5fd12bc3a778264f28011b7d3a90652.jpg",
    title: "Inside North Korea",
    description: "This is the story of the twists and turns, the great game, that drives the race to end 70 years of hostilities, and a historic summit with North Korea and a US president.",
    tagline: "",
    genre: [""],
    language: ["English"],
    country: ["United States"],
    stats: {
      likes: "",
      dislikes: "",
      rating: {
        imdb: 6.8,
        rottenTomatoes: "",
      },
    },
    tags: ["North Korea", "history", "global"],
    officialSite: "National Geographic",
    releaseDate: {
      day: 18,
      year: 2018,
      month: 6,
    },
    director: ["Robert Zakin"],
    durationMin: 49,
  }
];

export {
  docs
}